import type { SeriesText } from "../localize";

export default {
  title: "La quête du code de Byte et Ada",
  tagline: "Pense comme un programmeur, sans ordinateur !",
  cast: {
    ada: ["Ada", "Une fille qui adore les énigmes et qui a construit son propre robot."],
    byte: ["Byte", "Un robot qui fait exactement ce qu'on lui dit, ni plus ni moins."],
  },
  episodes: [
    {
      title: "Exactement ce que tu dis",
      topic: "Les algorithmes",
      summary: "Ada apprend à Byte à faire une tartine de confiture et découvre pourquoi les instructions doivent être précises.",
      takeaway: "Un algorithme est une liste d'étapes claires et précises, et l'ordre des étapes compte.",
      scenes: [
        ["", "Ada a construit un robot appelé Byte. Byte fait exactement ce qu'on lui dit, ni plus ni moins.", "Bip ! Bonjour, Ada. J'attends les instructions."],
        ["Algorithme", "Un algorithme est une liste d'étapes qui résout un problème. Apprenons à Byte à faire un sandwich à la confiture !", "Algorithme sandwich. Passionnant ! Prêt pour l'étape un."],
        ["Étape 1", "Étape un : mets de la confiture sur le pain.", "Byte pose le pot de confiture fermé sur la miche. Plop !"],
        ["Bug !", "Instruction terminée. La confiture est sur le pain.", "Ha ! Tu as raison. Je n'ai pas été assez précise."],
        ["Sois précis", "Les ordinateurs ne peuvent pas deviner ce qu'on veut dire. Chaque étape doit être claire et exacte.", "Correct. Je sais seulement ce qu'on me dit. Bip !"],
        ["Étapes 1 et 2", "Nouvel algorithme. Un : ouvre le pot. Deux : sors deux tranches de pain du sachet."],
        ["Étapes 3 et 4", "Trois : avec la cuillère, étale la confiture sur une tranche. Quatre : pose l'autre tranche dessus."],
        ["Sandwich !", "Byte suit chaque étape dans l'ordre et fait un sandwich à la confiture parfait !", "Sandwich terminé. Bip boup !"],
        ["L'ordre compte", "Question : et si je colle les tranches avant d'étaler la confiture ?", "Alors la confiture finit à l'extérieur. L'ordre des étapes compte !"],
        ["", "Les programmeurs écrivent des algorithmes tous les jours. Essaie d'écrire les étapes pour te brosser les dents, puis teste-les sur quelqu'un à la maison !"],
      ],
      quiz: [
        ["Qu'est-ce qu'un algorithme ?", ["Une liste d'étapes qui résout un problème", "Une sorte de robot", "Un mot de passe secret"], "Les algorithmes sont des instructions étape par étape."],
        ["Pourquoi Byte a-t-il posé tout le pot sur le pain ?", ["L'instruction n'était pas précise", "Byte faisait exprès de faire le clown", "Byte avait faim"], "Les ordinateurs suivent les instructions à la lettre, alors elles doivent être précises."],
        ["Que peut-il se passer si on change l'ordre des étapes ?", ["Le résultat peut changer", "Rien ne change jamais", "Le robot s'endort"], "Dans un algorithme, l'ordre compte."],
        ["Quelle instruction est la plus précise ?", ["Sors deux tranches de pain du sachet", "Fais-le joliment", "Fais le truc avec la nourriture"], "Des étapes claires et exactes marchent le mieux."],
      ],
    },
    {
      title: "Boucle la boucle",
      topic: "Les boucles",
      summary: "Ada apprend à Byte une danse et un dessin avec des boucles, et découvre que chaque boucle doit pouvoir s'arrêter.",
      takeaway: "Les boucles répètent des étapes pour gagner du temps, mais chaque boucle a besoin d'une règle pour s'arrêter.",
      scenes: [
        ["", "Ada apprend une danse à Byte.", "Pas à gauche, pas à droite, clap ! Pas à gauche, pas à droite, clap ! Pas à gauche...", "Bip ! Ces instructions deviennent très longues."],
        ["Boucle", "J'ai une idée ! On peut utiliser une boucle. Une boucle dit à l'ordinateur de répéter des étapes."],
        ["Répète 4 fois", "Répète quatre fois : pas à gauche, pas à droite, clap !", "Byte danse toute la chorégraphie avec une seule petite instruction."],
        ["Dessine un carré", "Maintenant, dessinons un carré. Avance, puis tourne à droite.", "J'avance. Je tourne à droite. J'attends d'autres étapes. Bip."],
        ["Répète 4 fois", "Avance, tourne à droite. Répète quatre fois. Carré terminé !"],
        ["Répète 5 fois", "Si on tourne plus fort et qu'on répète cinq fois, on obtient une étoile !", "Cinq branches ! Les boucles peuvent dessiner des motifs incroyables."],
        ["Boucle sans fin !", "Oh oh ! Ada a oublié de dire quand s'arrêter. Byte tourne, tourne et tourne encore.", "Je tourne pour toujours. Bip ! Au secours !"],
        ["Règle d'arrêt", "Oups, c'est une boucle infinie ! Chaque boucle a besoin d'une règle pour s'arrêter.", "Je m'arrête. Merci. J'avais la tête qui tournait !"],
        ["Des boucles partout", "Il y a des boucles partout : les feux répètent vert, orange et rouge, et les saisons reviennent chaque année.", "Même le refrain d'une chanson est une boucle !"],
        ["", "Les boucles font gagner du temps et raccourcissent le code. Bip boup !", "Trouves-tu une boucle dans ta journée ? Peut-être en brossant chaque dent !"],
      ],
      quiz: [
        ["Que fait une boucle ?", ["Elle répète des étapes", "Elle efface le programme", "Elle éteint le robot"], "Les boucles répètent des instructions."],
        ["Combien de fois répète-t-on « avance, tourne à droite » pour dessiner un carré ?", ["4", "2", "10"], "Un carré a quatre côtés, donc on répète quatre fois."],
        ["Qu'est-ce qu'une boucle infinie ?", ["Une boucle qui ne s'arrête jamais", "Une toute petite boucle", "Une boucle en ficelle"], "Sans règle d'arrêt, une boucle continue pour toujours."],
        ["Lequel est un exemple de boucle dans la vraie vie ?", ["Les feux qui répètent leurs couleurs", "Un seul éternuement", "Ouvrir une porte une fois"], "Les feux répètent le même motif encore et encore."],
      ],
    },
    {
      title: "La chasse aux bugs",
      topic: "Le débogage",
      summary: "Byte livre une lettre au mauvais endroit, et Ada apprend à tester, trouver et corriger le bug.",
      takeaway: "Déboguer, c'est tester, trouver et corriger les erreurs, et tous les programmeurs le font.",
      scenes: [
        ["Mission : bibliothèque", "Byte suit un programme pour livrer une lettre à la bibliothèque.", "Bip ! Lancement du programme de livraison."],
        ["", "Mais Byte arrive à la boulangerie à la place !", "Livraison terminée. Ça sent le pain ici."],
        ["Bug !", "Il y a un bug dans notre programme. Un bug, c'est une erreur qui fait faire la mauvaise chose au code.", "Un bug ? Je ne vois aucun insecte. Bip ?"],
        ["1947", "Le savais-tu ? En 1947, une équipe qui travaillait avec la pionnière de l'informatique Grace Hopper a trouvé un vrai papillon de nuit coincé dans un ordinateur !", "Ils l'ont collé dans leur carnet et ont écrit : premier vrai cas de bug trouvé."],
        ["Étape 1 : tester", "Déboguer, c'est trouver et corriger les bugs. D'abord, on teste pour voir exactement ce qui ne va pas.", "Test en cours. J'ai tourné à la fontaine et je suis arrivé à la boulangerie."],
        ["Étape 2 : trouver", "Je relis mes étapes. L'étape trois dit : tourne à droite à la fontaine.", "C'est ça ! Il fallait écrire : tourne à gauche !"],
        ["Canard en plastique !", "Certains programmeurs expliquent leur code à voix haute à un canard en plastique. Le dire à voix haute les aide à repérer les erreurs !"],
        ["Étape 3 : corriger", "On remplace droite par gauche. Corrigé !", "Mise à jour du programme. Bip !"],
        ["Étape 4 : retester", "Ils testent à nouveau. Cette fois, Byte arrive à la bibliothèque avec la lettre !", "Mission accomplie. Et pas de pain cette fois !"],
        ["", "Les bugs ne sont pas des échecs. Ce sont des indices !", "Tous les programmeurs font des bugs. Les bons programmeurs les testent, les trouvent et les corrigent."],
      ],
      quiz: [
        ["Qu'est-ce qu'un bug dans le code ?", ["Une erreur qui fait faire la mauvaise chose au code", "Un insecte de compagnie", "Un ordinateur rapide"], "Les bugs sont des erreurs dans les programmes."],
        ["Qu'a trouvé en 1947 une équipe de Grace Hopper dans un ordinateur ?", ["Un vrai papillon de nuit", "Un sandwich", "Un canard en plastique"], "Ils ont trouvé un papillon de nuit et l'ont collé dans leur carnet."],
        ["Quelle est la première étape du débogage ?", ["Tester pour voir ce qui ne va pas", "Jeter l'ordinateur", "Abandonner"], "Tester nous montre où est le bug."],
        ["Pourquoi certains programmeurs parlent-ils à un canard en plastique ?", ["Expliquer à voix haute aide à trouver les erreurs", "Les canards sont de super codeurs", "Ça accélère l'ordinateur"], "Expliquer ses étapes aide à repérer les problèmes."],
      ],
    },
  ],
} satisfies SeriesText;
