import type { SeriesText } from "../localize";

export default {
  title: "Les bricoleurs du temps",
  tagline: "Fonce à travers l'histoire pour découvrir les idées qui ont changé le monde.",
  cast: {
    max: ["Max", "Un garçon qui veut savoir comment tout fonctionne."],
    lina: ["Lina", "Une jeune inventrice qui démonte tout pour voir ce qu'il y a dedans."],
    tock: ["Tock", "Une tortue de deux cents ans qui pilote une machine à remonter le temps."],
  },
  episodes: [
    {
      title: "La roue arrive en roulant",
      topic: "La roue et l'essieu",
      summary: "Les bricoleurs remontent plus de cinq mille ans en arrière pour voir comment la roue et l'essieu ont été inventés.",
      takeaway: "La roue et l'essieu, inventés il y a plus de cinq mille ans, ont rendu beaucoup plus facile le transport des choses lourdes.",
      scenes: [
        ["", "Voici les bricoleurs du temps : Max, Lina et Tock, une tortue de deux cents ans avec une machine à remonter le temps.", "La question du jour : qui a inventé la roue ?"],
        ["3500 av. J.-C.", "Vrrr ! La machine remonte plus de cinq mille ans en arrière.", "Ouah, mon ventre fait des pirouettes !"],
        ["Mésopotamie", "Nous sommes en Mésopotamie, dans l'actuel Irak. C'est l'un des premiers endroits où l'on a construit des villes."],
        ["", "Regardez ! Avant la roue, on traînait les charges lourdes sur des traîneaux, ou on les faisait rouler sur des rondins.", "Ça a l'air épuisant !", "Les rondins marchaient, mais il fallait sans arrêt remettre celui de derrière devant. Trop lent !"],
        ["Le tour de potier", "Surprise : certaines des premières roues ne servaient pas à rouler. Les potiers faisaient tourner l'argile sur une roue pour faire des pots !"],
        ["Roue + essieu", "L'idée géniale, c'était l'essieu, une tige au milieu. La roue tourne autour pendant que le chariot reste stable."],
        ["", "Bientôt, des bœufs tiraient des chariots sur de lourdes roues en bois et portaient le grain au marché bien plus vite.", "Allez, le bœuf, allez !", "Bien plus tard, on a inventé les roues à rayons, plus légères et plus rapides."],
        ["Les roues aujourd'hui", "Les vélos, les voitures, les trains et même les skateboards roulent sur des roues et des essieux !"],
        ["Les engrenages", "Les engrenages sont des roues avec des dents. Ils se cachent dans les horloges, les vélos et les machines partout.", "Je savais que je trouverais des roues dans tout !", "Même une poignée de porte est une roue et un essieu déguisés !"],
        ["", "Une idée toute simple, un cercle qui tourne, a changé le monde entier.", "Où la machine à remonter le temps nous emmènera-t-elle la prochaine fois ?"],
      ],
      quiz: [
        ["Où certaines des premières roues ont-elles été inventées ?", ["En Mésopotamie", "En Antarctique", "Sur la Lune"], "Certaines des premières roues viennent de Mésopotamie, dans l'actuel Irak."],
        ["À quoi servaient certaines des premières roues ?", ["À faire des poteries", "À faire des courses de voitures", "À faire voler des cerfs-volants"], "Les potiers faisaient tourner l'argile sur des roues pour façonner des pots."],
        ["Qu'est-ce qu'un essieu ?", ["Une tige autour de laquelle tourne la roue", "Une sorte de cheval", "Une sorte de route"], "L'essieu permet à la roue de tourner pendant que le chariot reste stable."],
        ["Depuis quand utilise-t-on des roues sur les chariots ?", ["Plus de 5 000 ans", "100 ans", "La semaine dernière"], "Les chariots à roues sont apparus il y a plus de cinq mille ans."],
      ],
    },
    {
      title: "Que la lumière soit !",
      topic: "L'ampoule",
      summary: "Les bricoleurs découvrent combien d'inventeurs ont travaillé ensemble pour créer l'ampoule électrique.",
      takeaway: "L'ampoule est née de nombreux inventeurs qui ont construit sur les idées des autres, et la lumière électrique a changé la vie la nuit.",
      scenes: [
        ["", "Clic ! Les lumières du labo clignotent et s'éteignent.", "Sans ampoules, comment voyait-on la nuit ?", "Découvrons-le. À la machine à remonter le temps !"],
        ["Avant les ampoules", "Autrefois, on s'éclairait avec des bougies et des lampes à huile. Elles fumaient, éclairaient peu et pouvaient causer des incendies."],
        ["1879", "En 1879, dans le New Jersey, l'équipe de Thomas Edison a fabriqué une ampoule capable de briller pendant des heures.", "Ils ont testé des milliers de matériaux pour la partie qui brille, même du bambou !"],
        ["Travail d'équipe !", "Mais Edison n'était pas seul ! Joseph Swan fabriquait des ampoules en Angleterre, et beaucoup d'inventeurs ont aidé."],
        ["Le filament", "Dans l'ampoule, il y a un fil très fin appelé filament. Quand l'électricité le traverse, il chauffe tellement qu'il brille !"],
        ["Pas d'air dedans", "Ils ont retiré l'air du verre. Sans air, le filament chaud ne brûle pas aussi vite."],
        ["Lewis Latimer", "L'inventeur Lewis Latimer a trouvé une meilleure façon de fabriquer des filaments en carbone, pour des ampoules plus durables et moins chères."],
        ["Villes lumineuses", "Bientôt, la lumière électrique a éclairé les maisons et les rues du monde entier.", "La nuit est devenue beaucoup plus claire !", "Les usines pouvaient fonctionner la nuit, et on pouvait lire bien après le coucher du soleil."],
        ["Les LED", "Aujourd'hui, beaucoup de lampes sont des LED. Elles consomment beaucoup moins d'électricité et durent des années."],
        ["", "La prochaine fois que j'allume la lumière, je penserai à tous ces inventeurs !", "Les grandes inventions viennent souvent de nombreuses personnes qui construisent sur les idées des autres."],
      ],
      quiz: [
        ["Avec quoi s'éclairait-on avant les ampoules ?", ["Des bougies et des lampes à huile", "Des lampes de poche", "Des bâtons lumineux"], "Les bougies et les lampes à huile éclairaient les maisons autrefois."],
        ["Comment s'appelle le fil fin qui brille dans une ancienne ampoule ?", ["Un filament", "Une nouille", "Une clôture"], "L'électricité chauffe le filament jusqu'à ce qu'il brille."],
        ["Qui a trouvé une meilleure façon de fabriquer des filaments en carbone ?", ["Lewis Latimer", "Léonard de Vinci", "Isaac Newton"], "La méthode de Lewis Latimer a rendu les ampoules plus durables et moins chères."],
        ["Pourquoi utilise-t-on beaucoup de LED aujourd'hui ?", ["Elles consomment moins d'électricité", "Elles sont en bonbon", "Elles ne marchent que le jour"], "Les LED sont économes et durent longtemps."],
      ],
    },
    {
      title: "Le premier vol",
      topic: "Le premier avion",
      summary: "Les bricoleurs vont à Kitty Hawk en 1903 pour voir les frères Wright entrer dans l'histoire.",
      takeaway: "En 1903, les frères Wright ont réalisé le premier vol d'un avion à moteur en testant, en observant les oiseaux et sans jamais abandonner.",
      scenes: [
        ["", "Max plie des avions en papier.", "Comment a-t-on appris à piloter un vrai avion ?", "Attachez vos ceintures. Prochain arrêt : 1903 !"],
        ["Kitty Hawk, 1903", "Ils atterrissent sur des dunes venteuses à Kitty Hawk, en Caroline du Nord, le 17 décembre 1903."],
        ["Fabricants de vélos", "Wilbur et Orville Wright fabriquaient des vélos dans leur atelier de l'Ohio. Ils ont utilisé ce savoir-faire pour construire des machines volantes."],
        ["Apprendre des oiseaux", "Ils ont observé comment les oiseaux tordent le bout de leurs ailes pour tourner et garder l'équilibre.", "Ils ont copié l'idée en tordant les ailes avec des câbles. On appelle ça le gauchissement des ailes."],
        ["Soufflerie", "Ils ont même construit leur propre soufflerie pour tester plus de deux cents petites formes d'ailes.", "Tester, tester, et tester encore !"],
        ["La portance", "En avançant, les ailes courbées poussent l'air vers le bas, et l'air pousse l'aile vers le haut. Cette poussée s'appelle la portance."],
        ["12 secondes !", "Orville a volé pendant douze secondes et parcouru environ trente-sept mètres. C'était le premier vol d'un avion à moteur !"],
        ["4 vols", "Ils ont volé quatre fois ce jour-là. Le plus long vol a duré cinquante-neuf secondes !", "De douze secondes à presque une minute, en une seule journée !"],
        ["Aujourd'hui", "Aujourd'hui, les avions transportent des millions de personnes au-dessus des océans chaque jour.", "Et seulement soixante-six ans après Kitty Hawk, des astronautes sont allés sur la Lune !"],
        ["", "Ils ont continué à essayer sans jamais abandonner !", "Comme les frères Wright, chaque essai raté t'apprend quelque chose de nouveau."],
      ],
      quiz: [
        ["Qui a réalisé le premier vol d'un avion à moteur ?", ["Les frères Wright", "Thomas Edison", "Marie Curie"], "Orville et Wilbur Wright ont volé à Kitty Hawk en 1903."],
        ["Combien de temps a duré le tout premier vol ?", ["Environ 12 secondes", "Environ 12 heures", "Environ 12 jours"], "Le premier vol n'a duré que douze secondes !"],
        ["Qu'ont appris les frères en observant les oiseaux ?", ["Comment les ailes se tordent pour tourner et s'équilibrer", "Comment pondre des œufs", "Comment chanter"], "Les oiseaux tordent le bout de leurs ailes pour se diriger et s'équilibrer."],
        ["Qu'est-ce que la portance ?", ["La poussée vers le haut sur l'aile", "Le moteur de l'avion", "Le siège du pilote"], "La portance est la poussée vers le haut qui maintient les avions en l'air."],
      ],
    },
  ],
} satisfies SeriesText;
